### PR TITLE
reverted vertical metrics. Values in previous commit are incorrect

### PR DESCRIPTION
**Pull request by m4rc1e**
Accidently added the wrong values.

### CODE REVIEW

**Comment by Gue3bara** [comment]
is there any action required from my side?

**Comment by Gue3bara** [comment]
I've been trying to fix this merge conflict but the merge over terminal keeps giving me error that i need to merge 1st and when i try it refuses the order

**Comment by m4rc1e** [comment]
I'll sort this tomorrow. I need to do a rebase. Don't worry

**Comment by m4rc1e** [comment]
Fixed

**Pull request merged**
